.github/PULL_REQUEST_TEMPLATE.md

This PR adds a warning comment in the GitHub's Pull Request Template to remind about selecting this repository (`https://github.com/rootstrap/react-native-template`) as base branch instead of the upstream repository (`https://github.com/obytes/react-native-template-obytes`)
I made this change because I accidentally created a Pull Request in the wrong repository, and there's no way to change what is the default base branch when creating a new Pull Request.

chore: add warning in Pull Request template

---

.github/workflows/deploy-docs.yml
docs/astro.config.mjs
docs/pnpm-lock.yaml

This PR adds a new GitHub action for automatically building and deploying the docs to a GitHub Page.
Because it was an easy and nice to have feature, and so we can focus in other tasks, like updating the docs itself.
There should be no impact in the development process in any of the projects from this repository.
I created a new temporal branch with this changes, and I forced the GitHub action to run on that branch. [These are the logs](https://github.com/rootstrap/react-native-template/actions/runs/9700761907/job/26772950573).
The docs were deployed here: https://rootstrap.github.io/react-native-template/

chore(docs): add action for deploying docs

---

.github/actions/setup-node-pnpm-install/action.yml

Update the version of actions being used in github workflows.
On projects created by the current cli the github actions are failing.
Github workflows
The change was made on a project created using the CLI  until the actions passed.
You can check the result [here](https://github.com/fernandatoledo/MyApp/pull/1)

chore: update-action-version

---

EAS.md
README-project.md

Adds further instructions to be able to submit apps to the store through eas.
Even though the config is already there, there are some initial steps that need to be setup and there were some missing instructions.
Documentation for projects created using the CLI.
Building through eas a project created with the template and setting it up.

chore(eas): add-readme-instructions

---

.github/workflows/sonar.yml
README-project.md
jest.config.js

Add sonar scanner github action so that it's triggered on every pull request and push to gitflow branches.
At Rootstrap we use SonarQuube for continuous inspection of code quality, detect bugs, code smells, and security vulnerabilities. 
Github actions
This action will run on this PR and the status of the check will be shown.

chore: setup sonar scanner

---

.github/workflows/sonar.yml
cli/clone-repo.js
cli/index.js
cli/setup-project.js
cli/utils.js
env.js

- Use our repository as template when executing the CLI.
- Change some wordings like "Starter" to "Template", and change references from Obytes to Rootstrap.
- Refactor some code to reuse strings, or read them from the `package.json` file.
- TODO: The README file from the CLI project still needs to be changed.
- To start testing new changes from our template into new projects started from our CLI.
N/A
Running locally:
```shell
cd cli
./index.js MyTestApp
```
Then checking that the created project is consistent with what the CLI do.

feat(cli): use our repository as template

---

.github/workflows/lint-ts.yml
.github/workflows/test.yml
.github/workflows/type-check.yml

This PR changes the Lint, Test and Type Check GH Actions so they always run on any pull request, and not only the ones having main/master as base branch.
Because in some scenarios we have PRs for branches pointing to other branches than main/master and it's nice if we can start running checks on them.
Template maintainers.
Still untested. Will edit this comment with more information after these changes are applied.

chore(ci): run lint, test and type check on every pull request

---

.github/workflows/new-cli-version.yml

This PR adds a new GH Action to be used to build & publish a new version of the CLI.
- To avoid having to manually publish a new version from a local machine.
N/A
https://github.com/rootstrap/react-native-template/actions/runs/10223286450/job/28289351702

feat(cli): add GH action for publishing new version

---

src/api/common/interceptors.ts

Modifies the request config data only if there was a config set before
The request was failing due to the request config at the interceptor
Network layer
Tested the app locally
Before:
After:

Fix axios nterceptor

---

.github/workflows/upstream-to-pr.yml
cli/clone-repo.js
cli/setup-project.js
cli/utils.js

- This PR adds a new GitHub Action to check for upstream (obytes) changes and it creates a new branch and a PR with those changes. The action will automatically be triggered daily. It also allows for manual/API triggered checks (workflow_dispatch).
- It also modifies the `cli` app so new projects created with the latest `cli` version will also have this action, which will check if Rootstrap's Template repository has new changes to be merged to their project.
To automate, notify and control what changes we want to merge from the upstream repository (Obytes) to our template.
- **Template Maintainers** because, starting from now, new PRs will be automatically created and they'll have the responsibility to review them, decide and debate which changes from Obytes we want to include in our …

feat: add action for checking upstream for changes

---

.env.sample
.github/workflows/expo-doctor.yml
env.js

- Remove example values from `.env.sample` to minimize mistakes.
- Remove environment variables from `expo-doctor.yml` workflow.
- Remove `prebuild` step from `expo-doctor.yml` workflow.
- Add more type-checking to `env.js` file.
- Add `parseString`, `parseNumber` and `parseBoolean` utility functions.
To avoid having to define dummy values to all environment variables in order to run expo doctor.
Devs using the template.
WIP

chore: remove environment variables from expo-doctor workflow

---

docs/src/content/docs/ci-cd/app-releasing-process.mdx
docs/src/content/docs/ci-cd/workflows-references.mdx

Fix docs project not building.
Because the docs project deployment was failing. See [logs](https://github.com/rootstrap/react-native-template/actions/runs/10692121403/job/29639956077).
Docs users.
1. Running `pnpm run build` in `docs` directory and veryfing that the build was failing locally.
2. Fixing the issues locally.
3. Running `pnpm run build` again and verifying that it does build successfully.

build(docs): fix docs project not building

---

.eslintrc.js
package.json
pnpm-lock.yaml
src/components/login-form.test.tsx
src/ui/button.tsx
src/ui/checkbox.test.tsx
src/ui/input.test.tsx
src/ui/progress-bar.test.tsx

Adds [sonarJS plugin for ESLint](https://github.com/SonarSource/SonarJS/blob/master/packages/jsts/src/rules/README.md) this will be able to identify some errors that would make sonarqube fail while coding.
This would save some time detecting issues beforehand instead of finding them only after sonarqube has failed.
Dev experience
I run pnpm lint locally, new errors were thrown after installing the plugin.
BTW: 
We're currently using an old version of ESLint, this will be updated on future PRs

chore: add sonarjs plugin for eslint

---

.eslintrc.js
.github/workflows/sonar.yml
scripts/i18next-syntax-validation.js
src/api/common/axios.d.ts
src/api/common/utils.tsx
src/core/i18n/types.ts
src/core/i18n/utils.tsx
src/core/utils.ts

There's a rule that sonar is applying but we didn't have configured on our Eslint: [The "any" type should not be used](https://sonarqube-developers.rootstrap.net/coding_rules?open=typescript%3AS4204&rule_key=typescript%3AS4204)
So that this issues don't come up on sonar anymore.
Dev experience
Linting locally

chore(sonar): unexpected any specify a different type

---

EAS.md

Add one instruction to the EAS configuration docs about adding envfiles to eas secrets
There was a missing step in the docs
Docs and dev experience
Manually by running GHA to build EAS

docs: add instructions to upload envfiles to eas secrets

---

docs/src/components/GithubStar.astro

Fixes the repo the component `GithubStar.astro` to fetch stars from the Rootstrap Template repo.

fix: fix github stars point to rs repo

---

cli/clone-repo.js
cli/index.js
cli/project-files-manager.js
cli/setup-project.js

Create a `ProjectFilesManager` class to manage common file operations (removing, renaming and replacing files). It includes types annotations.
- To avoid code repetition within CLI functions.
- To centralize common file operations in one place.
- To have a declarative way to execute those common file operations.
Developers of the CLI project.
I created a new application with the current version of the CLI, without these changes. Then I created another application with this new CLI, and I compared both projects. As this is just a refactor and no new functionality is being implemented, the two projects should and did have the same contents.

refactor(cli): move file operations to ProjectFilesManager class

---

.eslintrc.js
src/api/common/utils.tsx

Adds rule on eslint to be aligned with rule from Sonar: https://sonarqube-developers.rootstrap.net/coding_rules?open=typescript%3AS1535&rule_key=typescript%3AS1535
The for...in statement allows you to loop through the names of all of the properties of an object. The list of properties includes all those properties that were inherited through the prototype chain. This has the side effect of serving up functions when the interest is in data properties. Programs that don’t take this into account can fail.
Therefore, the body of every for...in statement should be wrapped in an if statement that filters which properties are acted upon. It can select for a particular type or range of values, or it can exclude functions, or it can exclude properties from the prototype.
Coding experience
N/A

chore: guard-for-in

---

cli/setup-project.js

Remove `.github/workflows/deploy-cli.yml` and `.github/workflows/deploy-docs.yml` files as part of the project setup process.
Because it doesn't make sense to have those workflows in the context of a project.
N/A
Locally ran the CLI to create a new project and verifying that the mentioned files were not present.

fix(cli): remove docs & CLI deploy workflows

---

cli/setup-project.js

Remove warning from Pull Request Template file as part of the project setup process.
Because it doesn't make sense to have that warning in the context of a project.
N/A
Locally running the CLI to create a new project and verifying that the warning not present.

fix(cli): remove warning from Pull Request Template

---

cli/setup-project.js

Add project name to README and add project slug to Expo config as part of the project setup process.
Because otherwise newly created apps will still have the default app name.
This should only affect new projects.
Locally running the CLI to create a new project and verifying that the project README file has now the project name, and that Expo config contains the lowercased project name as slug.

fix(cli): set project name in README and Expo config

---

.eslintrc.js
cli/utils.js
src/app/(app)/_layout.tsx
src/app/feed/add-post.tsx
src/components/login-form.tsx
src/core/i18n/index.tsx
src/ui/modal.tsx
src/ui/select.tsx
src/ui/text.tsx
src/ui/utils.tsx

Add the following rules to eslint:
- [Prefer using nullish coalescing operator (`??`) instead of a logical or (`||`), as it is a safer operator.](https://sonarqube-developers.rootstrap.net/project/issues?issues=AZDwG1Y54bsPZPlqsehk&open=AZDwG1Y54bsPZPlqsehk&id=react-native-template) rule to eslint.
- [Magic numbers should not be used](https://sonarqube-developers.rootstrap.net/coding_rules?open=typescript%3AS109&rule_key=typescript%3AS109) 
There were some issues reported by sonarqube
Get issues while coding thanks to ESLint.

chore: no-magic-number

---

.husky/commit-msg
.husky/pre-commit

1. This PR fixes the pre-commit hook to work with new repositories, i.e. when a new project is created from the CLI and a developer tries to create an initial commit. The issue was being caused by the command that is responsible of retrieving the current branch name. Replacing it with `git branch --show-current` solved the issue.
2. This PR also addresses a warning from husky v9, removing deprecated code.
1. `git rev-parse --abbrev-ref HEAD` doesn't work for new repositories:
```shell
$ mkdir new-project
$ cd new-project
$ git init .
Initialized empty Git repository in /Users/asdolo/dev/new-project/.git/
$ git rev-parse --abbrev-ref HEAD
HEAD
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git …
```

fix(husky): pre-commit hook not working for new projects

---

src/core/i18n/index.tsx

Stops using a deprecated function and it replaces it with the right function. Read more about it in the documentation: https://docs.expo.dev/versions/latest/sdk/localization/#constants
The locale constant was deprecated.
Localization
Just tried changing the language and make sure it still worked
https://github.com/user-attachments/assets/9c23d217-5898-4599-9383-520e17ae2077

fix: use getLocales instead of deprecated locale

---

.github/workflows/lint-ts.yml
.github/workflows/test.yml
.github/workflows/type-check.yml

This PR changes the Lint, Test and Type-Check workflows to specifically set the minimum permissions they need.
The workflows (and thus, the status checks of all Pull Requests and pushes) weren't working if the default permissions granted to the `GITHUB_TOKEN` were set to "Read" instead of "Read and Write" in the project repository.
Nonetheless, [GItHub recommends](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#permissions) to "only allow the minimum required access" to the workflow files.
- The `GITHUB_TOKEN` secret is used by all of these workflows to perform operations such as reading our PRs and creating comments on them.
- If no `permissions` are specified in a workflow file, the `GITHUB_TOKEN` will have the default permissions set in the …

fix(ci): status check workflows permissions

---

.github/workflows/check-merge-conflicts.yml

This PR adds a new GitHub workflow that checks if there are unresolved conflicts in the code and it fails if they are.
- To add an extra safety check in our pipeline.
- It is part of a bigger task that involves automating the update process of a project that was created using this template. That automation script tries to solve merge conflicts as best as possible, but in some cases it introduces some merge conflicts that GitHub's interface doesn't show as Merge Conflict in the Pull Request page.
Every project using the next version of the template. They should add the new "check-conflicts" check in their branch protection ruleset: (Repository settings > Rules > Rulesets > Select branch protection ruleset > Expand "Require status checks to pass" rule > Click on "Add checks" and select the …

feat: add workflow for checking unresolved conflicts

---

.github/project-workflows/sync-with-template.yml
cli/setup-project.js
docs/src/content/docs/ci-cd/workflows-references.mdx
docs/src/content/docs/guides/upgrading-deps.mdx

This PR adds a new GitHub workflow for automatically syncing a project with the latest releases of the template. The workflow runs automatically every day. It checks if there's a new template version and it creates a new Pull Request with the diff between the latest version and the last one used by the project.
To help project keeping their codebase updated.
New projects will now be able to update to upcoming template releases.
We manually added the workflow to a project and tested how it performed.

feat: add workflow for projects to sync with new template versions

---

.vscode/i18n-ally-custom-framework.yml

Update configuration for vscode's `i18n-ally` extension so it can detect calls to `translate` function. 
Because currently `i18n-ally` is programmed in a way that it only detect calls to the `t` function, but we are using a custom wrapper function of it (`translate`), and it isn't being detected by the extension.
With this change, we can now _see_ actual translations in the code and interact with them using the extension:
| Before | After |
| - | - |
| <img width="650" alt="image" src="https://github.com/user-attachments/assets/c255804e-c582-417b-b7de-9992c5d67488"> | <img width="501" alt="image" src="https://github.com/user-attachments/assets/cf15a1c7-3586-4444-990f-b5b0a937bc15"> |
https://github.com/user-attachments/assets/19cd782b-f212-4b13-9dd0-a829cb1279d9
With the new config file …

fix(vscode): i18n-ally not showing inline annotations

---

.github/workflows/new-template-version.yml

This PR fixes a bug in the `new-template-version.yml` workflow that prevented `deploy-docs.yml` workflow not to trigger automatically. It also replaces the old classic `GH_TOKEN` token with a modern fine-grained token (`NEW_TEMPLATE_VERSION_PAT`).
The problem was that the old token didn't have [enough permissions](https://github.com/orgs/community/discussions/54574#discussioncomment-10119733) to trigger another workflow.
To fix this bug, which was introduced in [this PR](https://github.com/rootstrap/react-native-template/pull/70).
It affects the documentation deployment process. It also impacts people reading the documentation, who will now be reading the version corresponding to the latest version of the template.
I pushed this changes in a private fork and ensured both workflows ran as …

fix(ci): docs not being deployed automatically when releasing a new template version

---

cli/package.json

Add `project-files-manager.js` to the CLI build.
Because it was missing from the build, and it was causing the CLI to crash when trying to import the file:
```shell
node:internal/modules/cjs/loader:1051
throw err;
^
Error: Cannot find module './project-files-manager.js'
Require stack:
- /Users/asdolo/.npm/_npx/fd426691c5ece2b5/node_modules/create-rootstrap-rn-app/setup-project.js
- /Users/asdolo/.npm/_npx/fd426691c5ece2b5/node_modules/create-rootstrap-rn-app/index.js
at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
at Module._load (node:internal/modules/cjs/loader:901:27)
at Module.require (node:internal/modules/cjs/loader:1115:19)
at require (node:internal/modules/helpers:119:18)
at Object.<anonymous> (/Users/asdolo/.npm/_npx/fd426691c5ece2b5/node_modules/create-roots …
```

fix(cli): ProjectFilesManager class not being included in build

---

src/api/auth/use-login.ts
src/app/_layout.tsx
src/app/sign-in.tsx
src/components/login-form.test.tsx
src/components/login-form.tsx

Adds sign-in functionality that would work with our BlackMarket API.
Auth functionality.
Set the `API_URL` env variable to `https://rs-blackmarket-api.herokuapp.com/api` and test sign-in flow.

feat: sign in

---

app.config.ts

Adds missing expo-dev-client plugin to app.js, this plugin is required to be able to build using eas build correctly. https://docs.expo.dev/versions/latest/sdk/dev-client/#example-appjson-with-config-plugin
Eas build was finishing successfully and eas update too, but when was needed to install the app in a device it said that it was not a valid version.
Eas builds and updates
Using eas build and eas update and installing the app on a physical iOS device.

fix: eas build devclient

---

src/api/auth/use-user.tsx
src/app/(app)/settings.tsx
src/components/settings/delete-account-item.tsx
src/components/settings/item.tsx
src/translations/en.json

Adds delete account feature.
To complain with the App Stores we need to allow users to delete their account. This feature will enable users to do it from the settings screen.
1) Create a user.
2) Navigate to the Settings screen and press delete.
3) Confirm the deletion.
4) Try to log in again with the same credentials.
https://github.com/user-attachments/assets/5682a691-5dec-4771-91f0-7054272b292f

feat: add delete account feature

---

src/api/common/utils.spec.tsx
src/api/common/utils.tsx

There’s an util function: toSnakeCase and toCamelCase that are used in the interceptor to parse all payload in requests and response. This function is not working properly for nested objects.
It's common that the payload sent or received contains nested objects and those keys need to be parsed as well.
Payload in response and requests.
Unit tests have been added

fix: parse nested objects
